#-------------------------------
# General Site Settings
title: Porfolio
logo: # logo.svg # You can add own logo.
description: Portfolio of Vojta Šafránek


#-------------------------------
# Author Settings
author:
  name: Vojta Šafránek
  image: photo.JPG
  say-hello: Hello, I’m <strong>Vojta Šafránek</strong>
  bio: a customer oriented <strong>UX Designer</strong> with background in Informatics, business savvy Analyst and a&nbsp;certified Scrum Master. I&nbsp;have experience with working on projects in Mobility & HealthTech and I'm especially knowledgeable in <strong>FinTech</strong>. I&nbsp;am fascinated by the ways how technology shapes our world and I have a strong focus on <strong>digital ethics</strong>. I&nbsp;also make pretty damn good cocktails and some people think that I'm funny.
# <a href="#">link</a>

#-------------------------------
# Contact links
twitter: # Add your Twitter handle
facebook:  # Add your Facebook handle
dribbble:  # Add your Dribbble handle
instagram:  # Add your Instagram handle
pinterest:  # Add your Pinterest handle
linkedin: https://www.linkedin.com/in/vojtasaf/?locale=en_US # 
mail: mailto:vojtech.safranek@gmail.com # 


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-151321747-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e