#-------------------------------
# General Site Settings
title: Porfolio
logo: # logo.svg # You can add own logo.
description: Portfolio of Vojta Šafránek


#-------------------------------
# Author Settings
author:
  name: Vojta Šafránek
  image: photo.jpg
  say-hello: Hello, I’m <strong>Vojta Šafránek</strong>
  bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
twitter: # Add your Twitter handle
facebook:  # Add your Facebook handle
dribbble:  # Add your Dribbble handle
instagram:  # Add your Instagram handle
pinterest:  # Add your Pinterest handle
linkedin: https://www.linkedin.com/in/vojtasaf/?locale=en_US # 
mail: mailto:vojtech.safranek@gmail.com # 


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e